### ISSUE TITLE
A line of papers on recent "harmful fine-tuning" attack

### ISSUE THREAD

**Issue by huangtiansheng** [niconi19/LLM-Conversation-Safety#3]
Hi authors,

Thanks for the wonderful repo. Recently there is a growing interest on harmful fine-tuning issue for LLMs. Could you please include this line of papers into your repo?

We also maintain a survey&repo speficially for attacks/defenses for harmful fine-tuning. Please feel free to check them out.

Harmful Fine-tuning Attacks and Defenses for Large Language Models: A Survey https://arxiv.org/abs/2409.18169

Repo: https://github.com/git-disl/awesome_LLM-harmful-fine-tuning-papers

**Comment by niconi19** [comment]
Thank you very much for your kind words and for bringing this important topic to our attention. We truly appreciate your interest in our repository and recognize the critical importance of addressing harmful fine-tuning issues in LLMs. Your survey and repository offer a valuable resource to the community, and we will update our repository to include this series of papers as we learn from your work. Thank you once again for your contribution!

**Comment by huangtiansheng** [comment]
Thank you for your acknowledgement! We will also update our repo to include a link to this repo.
